### PR TITLE
Add CoC Contact info

### LINKED ISSUE #12: Code of Conduct missing contact info

### PR DESCRIPTION
**Pull request by badboy**
Closes #12

### CODE REVIEW

**Comment by untitaker** [comment]
Cool, thanks!

**Comment by Hoverbear** [comment]
@untitaker Are you coming to RustFest? :)

**Comment by untitaker** [comment]
Yup, but not arriving any sooner than 16th in the evening

**Comment by Hoverbear** [comment]
@untitaker Would you like to help with the web workshop? :)

**Comment by untitaker** [comment]
If there's a list of what you need help with I may be able to help :D

**Comment by Hoverbear** [comment]
@untitaker Maybe send me a Tweeter DM today and we can chat? https://twitter.com/andrewhobden

**Pull request merged**
