### PR TITLE
Improve Mobile Layout

### PR DESCRIPTION
**Pull request by killercup**
Basically, I fiddled until it looked useable on a small screen (320px).

cc @badboy

### CODE REVIEW

**Comment by badboy** [comment]
:+1: I'll take a look ASAP

**Comment by skade** [comment]
Looks not more broken then before, we'll try that out :)

**Comment by skade** [comment]
After deploying and trying on an actual device: that looks _much_ better.

**Comment by killercup** [comment]
I'm glad you like it! Let me know if you have any questions or want to change it some more! :)

**Pull request merged**
